Fixing cards
JSConfCL/getfunds pull request #14
Opened 2023-11-21 04:35 UTC by fforres

2023-11-21 10:45 UTC, joseglego approved these changes

2023-11-21 10:46 UTC, joseglego commented on src/components/Features/Perks.tsx
> +const PerkCard = ({
<3

2023-12-09 20:37 UTC, rodrigobustamante requested changes

2023-12-09 20:37 UTC, rodrigobustamante commented on src/components/Features/Donaciones.tsx
>  export const Donaciones = () => {
Podríamos dejar definido si vamos a definir componentes en inglés o en español 👀

2023-12-09 20:37 UTC, rodrigobustamante commented on src/components/Features/Perks.tsx
> +              title="Wall of Fame"
Estos strings sueltos podrían quedar como constantes, o pensando en i18n, podrían quedar como palabras de diccionario

2023-12-10 04:49 UTC, fforres commented on src/components/Features/Donaciones.tsx
>  export const Donaciones = () => {
Touche

2023-12-10 04:49 UTC, fforres commented on src/components/Features/Perks.tsx
> +              title="Wall of Fame"
Me parece :) 
Es algoq  buscamos ahora? IMO hagamos la migracion cuando tengamos una idea de como vamos a hacer i18n 🤔

2023-12-10 04:50 UTC, fforres commented on src/components/Features/Donaciones.tsx
>  export const Donaciones = () => {
Dejémoslo en Ingles

2023-12-10 04:53 UTC, merged